#!/bin/bash
source ~/.bashrc
set -euxo pipefail
cd -- "$( dirname -- "${BASH_SOURCE[0]}" )"
timeout 15 git pull || true
cargo build --release
BIN=$(pwd)/target/release/tiny-media-center
cd /media
exec "$BIN"
