# RPM spec for Fedora Copr. The SRPM is generated by .copr/Makefile, which
# vendors the Rust dependencies (Copr's mock builders have no network) and
# rewrites the Version below (from Cargo.toml, the single source of truth)
# and the two defines (HEAD committer timestamp + short hash) in place, so
# every build produces a newer EVR. They must be baked into the spec rather
# than passed as rpmbuild --define flags: Copr imports the SRPM's spec into
# its dist-git and re-evaluates it fresh in every chroot, where ephemeral
# defines would fall back to these placeholders.
%define snapdate 0
%define shortcommit local

Name:           tiny-media-center
Version:        0.0.0
Release:        1.%{snapdate}git%{shortcommit}%{?dist}
Summary:        Tiny fullscreen media center for keyboard/remote/gamepad use

License:        GPL-2.0-or-later
URL:            https://github.com/JanPokorny/tiny-media-center
Source0:        %{name}-%{version}.tar.gz
Source1:        %{name}-%{version}-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 25
BuildRequires:  gcc
BuildRequires:  pkgconfig(mpv)
# Fedora packages SDL3, so link it dynamically instead of the vendored
# static build used for the portable GitHub Releases binary.
BuildRequires:  pkgconfig(sdl3)

# libmpv.so.2 is picked up automatically; mpv-libs ships it since mpv 0.35.

%description
A tiny fullscreen media center for keyboard/remote/gamepad use: browse a
media directory, play videos through embedded mpv (with per-video
audio/subtitle track memory and watch progress), launch Wii games through
Dolphin, run shell scripts. Written in Rust on SDL3 + femtovg + libmpv.

%prep
%autosetup -a1
%cargo_prep -v vendor

%build
%cargo_build -n
%cargo_vendor_manifest

%install
install -Dpm0755 target/rpm/%{name} %{buildroot}%{_bindir}/%{name}

%files
%{_bindir}/%{name}
%license LICENSE
%license cargo-vendor.txt
%doc README.md

%changelog
* Thu Jul 16 2026 Jan Pokorny <jenompokorny@gmail.com> - 0.1.0-1
- Initial Copr packaging
